sudo: true
language: cpp
os:
- osx
compiler:
- gcc
cache:
  directories:
  - "$HOME/deps"
before_install:
- brew install freeimage fftw glfw
- |
  wget --show-progress --progress=dot https://arrayfire.s3.amazonaws.com/3.5.0/ArrayFire-v3.5.0_OSX.pkg
  sudo installer -pkg ArrayFire-v3.5.0_OSX.pkg -target /
script:
- curl -L https://cdn.jsdelivr.net/gh/InsightSoftwareConsortium/ITKPythonPackage/scripts/macpython-download-cache-and-build-module-wheels.sh -O
- chmod u+x macpython-download-cache-and-build-module-wheels.sh
- ./macpython-download-cache-and-build-module-wheels.sh
- tar -zcvf dist.tar.gz dist/
- curl --upload-file dist.tar.gz https://transfer.sh/dist.tar.gz
